# -*- coding: utf-8 -*-
"""Q5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bA-rAWqrrL_xrLS1KopsJG6-ccogS4CA
"""

def house():
  print("1. Electricity(House) Bill:")
  unit=int(input("Enter the number of units used: "))
  if(unit <= 100):
    bill = unit * 0.50
  elif unit >= 101 and unit <= 200:
    bill = 50 + ((unit - 100) * 0.75)
  elif unit >= 201 and unit <= 300:
    bill = 50 + 75 + ((unit - 200) * 1.20)
  elif (unit >= 300):
    bill = 50 + 75 + 120((unit-300) * 1.50)
  else:
    print("Eneter a valid unit")
  print("Bill per unit:",bill)
house()

import pandas as pd
data=pd.DataFrame(
    {"Student_Name": ['Parag','Kali','Aryan','Tulsi','Smiles','Paras','Karan','Arya','Gopi','Sam'],
     "Age": [20,21,22,23,24,25,26,27,28,29],
     "DOB": [2001,2002,2003,2004,2005,2006,2007,2008,2009,2010],
     "Weight(kg)" : [72,95,75,56,98,55,70,62,70,65],
     "Height(cm)" : [150,140,125,157,156,188,199,154,177,133]}
)

data["BMI"]=data["Weight(kg)"]/data["Height(cm)"]*data["Height(cm)"]
data["Status"]=data["BMI"].apply(lambda x: "Normal" if x>50 and x<80 else "Underweight")
print(data)



malware={'adwar':'tracks Client activity',
        'Botnet':'infected and commanded by the hacker/attcker',
        'keylogger':'A keylogger can monitor a great deal of user activity, including email, browsing activity, program,information ',
        'spyware':'like adware'}
print(malware)
print(len(malware))
print(type(malware))
malware['trojon']='trojon is a malware it attack unexpeted time'
print(malware)
malware.update({'adwar': ''})
print(malware)
malware.pop('spyware')
print(malware)
malware.clear()
print(malware)

print("we have to calcuate Gst(18%) on 12,300")
price=12300
GST=price*(18/100)
Totalprice=price+GST
print("GOOD AND SERVICE TAX on 12,300 is",GST)
print("Toatl price including GST",Totalprice)